[files]
extend-exclude = [
  "admin/src/main/resources/**",
  "admin/webapp/websrc/assets/img/country-flag/**"
]

[default.extend-words]
acess = "acess"
addmission = "addmission"
assemblys = "assemblys"
Backgound = "Backgound"
Boostrap = "Boostrap"
buil = "buil"
childs = "childs"
conjuntion = "conjuntion"
EDE = "EDE"
effectivelly = "effectivelly"
fo = "fo"
3DES_EDE_CBC = "3DES_EDE_CBC"
Implicits = "Implicits"
Impovement = "Impovement"
indx = "indx"
initialzation = "initialzation"
intecepting = "intecepting"
IST = "IST"
CAHCE = "CAHCE"
Kubernates = "Kubernates"
margings = "margings"
comliance = "comliance"
complaince = "complaince"
copile = "copile"
creater = "creater"
dashbaord = "dashbaord"
Descrition = "Descrition"
destory = "destory"
Diplay = "Diplay"
enpoint = "enpoint"
flourescent = "flourescent"
generater = "generater"
hightlighted = "hightlighted"
Implict = "Implict"
Mainfest = "Mainfest"
Nework = "Nework"
poilcy = "poilcy"
priviledge = "priviledge"
Priviledge = "Priviledge"
protocal = "protocal"
recommened = "recommened"
Refeshing = "Refeshing"
regestries = "regestries"
Registy = "Registy"
registy = "registy"
requset = "requset"
Reponse = "Reponse"
RETRIVE = "RETRIVE"
Resoureces = "Resoureces"
ROMOVE = "ROMOVE"
seleceted = "seleceted"
Slected = "Slected"
secutiry = "secutiry"
squence = "squence"
tiemout = "tiemout"
togglable = "togglable"
trimed = "trimed"
UPGADE = "UPGADE"
Verion = "Verion"
vulnerabilies = "vulnerabilies"
vulnerabilites = "vulnerabilites"
