[files]
extend-exclude = [
  "admin/src/main/resources/**",
  "admin/webapp/websrc/assets/img/country-flag/**",
  "java.security",
  "licenses/ui-licenses.txt",
]

[default.extend-words]
fo = "fo"
3DES_EDE_CBC = "3DES_EDE_CBC"
IST = "IST"
